<?php
/*
 * This file is part of the FileConverter package.
 *
 * (c) Greg Payne
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace FileConverter\Tests;

use FileConverter\FileConverter;

/**
 * Convert a small Word document to HTML through the docx->html Pandoc path.
 *
 * The fixture (Resources/docx-html.docx) is generated by Pandoc from
 * Resources/docx-html.md:
 *   cd src/Tests/Resources
 *   docker run --rm -v "$PWD":/data pandoc/core docx-html.md -o docx-html.docx
 * It holds a Heading 1, a Heading 2, a tracked insertion and deletion, a list,
 * a table and an embedded image.
 *
 * Skipped when pandoc is not installed. LaTeX is not needed for HTML output.
 */
class PandocDocxHtmlTest extends \PHPUnit\Framework\TestCase {
  protected $dir = NULL;

  protected function tearDown(): void {
    if (isset($this->dir) && is_dir($this->dir)) {
      $this->removeDirectory($this->dir);
    }
  }

  public function testDocxToHtml() {
    $fc = FileConverter::factory(FALSE);
    $engines = $fc->getEngines('docx->html', NULL, FALSE);
    $this->assertEquals('FileConverter\Engine\Convert\Pandoc', get_class($engines[0]));
    if (!$engines[0]->isAvailable()) {
      $this->markTestSkipped('pandoc is not installed.');
    }

    // The caller names the media directory on top of the default path.
    $this->dir = sys_get_temp_dir() . '/fileconverter-test-' . uniqid();
    mkdir($this->dir, 0755, TRUE);
    $media = $this->dir . '/extract';
    $configuration = $engines[0]->getConfiguration();
    $configuration['extract-media'] = $media;
    $configuration['#final'] = TRUE;
    $fc->setConverter('docx->html', $configuration);

    $destination = $this->dir . '/out.html';
    $fc->convertFile(__DIR__ . '/Resources/docx-html.docx', $destination);
    $this->assertFileExists($destination);
    $html = file_get_contents($destination);

    // Headings are demoted one level: Heading 1 -> <h2>, Heading 2 -> <h3>.
    $this->assertEquals(0, preg_match('@<h1[ >]@', $html), $html);
    $this->assertEquals(1, preg_match('@<h2[^>]*>Handbook Chapter</h2>@', $html), $html);
    $this->assertEquals(1, preg_match('@<h3[^>]*>Handbook Section</h3>@', $html), $html);

    // Tracked changes are accepted.
    $this->assertEquals(1, preg_match('@Accepted inserted words remain here\.@', $html), $html);
    $this->assertEquals(0, preg_match('@removed words@', $html), $html);

    // The list and the table survive.
    $this->assertEquals(1, preg_match('@<ul[^>]*>\s*<li>First item</li>\s*<li>Second item</li>\s*</ul>@', $html), $html);
    $this->assertEquals(1, preg_match('@<td[^>]*>Alpha</td>\s*<td[^>]*>Chair</td>@', $html), $html);
    $this->assertEquals(1, preg_match('@<td[^>]*>Beta</td>\s*<td[^>]*>Member</td>@', $html), $html);

    // The image is written under <extract-media>/media/ and referenced there.
    $images = glob($media . '/media/*');
    $this->assertCount(1, $images);
    $this->assertEquals(file_get_contents(__DIR__ . '/Resources/docx-html.png'), file_get_contents($images[0]));
    $this->assertEquals(1, preg_match('@<img src="' . preg_quote($images[0], '@') . '"@', $html), $html);
  }

  protected function removeDirectory($dir) {
    foreach (scandir($dir) as $item) {
      if ($item === '.' || $item === '..') {
        continue;
      }
      $path = $dir . '/' . $item;
      if (is_dir($path) && !is_link($path)) {
        $this->removeDirectory($path);
      }
      else {
        unlink($path);
      }
    }
    rmdir($dir);
  }

}
